### ISSUE TITLE
Sometimes, when restarting the server or the script you get these errors, and players can't see the npc's

### ISSUE THREAD

**Issue by pijus-x** [zRxnx/zrx_blackmarket#5]
Here are the errors
script:zrx_blackmarket SCRIPT ERROR: @zrx_blackmarket/client/client.lua:77: attempt to index a nil value (field '?')
And this one to, especially when the server restarts, and now you can't see the npc anymore, till you restart the script
script:zrx_blackmarket SCRIPT ERROR: @zrx_blackmarket/client/client.lua:113: failed to load animDict 'mini@strip_club@idles@bouncer@base' (waited 1.1ms)
script:zrx_blackmarket > [global chunk] (@ox_lib/imports/waitFor/client.lua:33)
script:zrx_blackmarket > fn (@zrx_blackmarket/client/client.lua:113)

**Comment by zRxnx** [comment]
That means your pc is too slow to load the anim OR it doesnt exist
